README.md, working-groups/meta/FAQ.md, working-groups/meta/NOTES.md, working-groups/meta/README.md
@nikomatsakis @davidtwco I've followed what the template suggests but I've figured out that it's a bit different to the style that the rest of the working groups are using. Unsure if we should migrate the rest or what's the idea.
In the NOTES.md file, I've used what we had on paper. It probably lacks a lot of info. Should I just read the meeting and do a brief recap?.
In the README.md check mainly the goals of the WG and I'm not sure who leads the working group so I've added only @nikomatsakis for now.
=> Add Meta WG

working-groups/self-profile/NOTES.md
=> Add links to the self-profiler tracking issue in the meeting notes

working-groups/meta/NOTES.md
You can see on [this page](https://github.com/rust-lang/compiler-team/blob/master/working-groups/meta/NOTES.md) that the link is currently broken.
=> Fix broken link in meta notes.

working-groups/polonius/minutes/2019.03.07-meeting.md
We don't have the expected documents for the WG yet, but here are the minutes for yesterday's meeting.
=> Polonius WG: add minutes for the 2019/03/07 meeting

README.md
Google asked me to login to view the old link. This link can be viewed publicly. You can still click the "+" link in the bottom right if you want to add the calendar to your Google calendar.
=> Update calendar link

procedures/crates.md
I've tried to write up what was discussed and in the notes from the All Hands' organizational meeting. There are a handful of areas that need elaborated on and might not make complete sense as it is but was mentioned in the notes from the meeting. I'd appreciate any further ideas or feedback.
=> Add initial draft of crates policy.

README.md, experts/MAP.md
@nikomatsakis @davidtwco we agreed on adding a document here that links the experts map.
Now I wonder, shouldn't we do the opposite?, I mean, build a table in this repo and link from the hackmd to this place just in case people have the old link.
The downside is that it's a bit more involved to add/remove/change stuff on github because requires a PR. But I guess this is "stable" now?.
=> Add experts map to the repo

working-groups/meta/README.md
@nikomatsakis @davidtwco planning doc is linked from the meta-wg README file.
=> Link planning doc from the README.md meta-wg file

working-groups/meta/rfc-drafts/README.md, working-groups/meta/rfc-drafts/compiler-team-contributors.md
This is a draft of an RFC to create a "compiler team contributors" grouping.
=> RFC: Compiler team contributors

minutes/triage-meeting/2019-04-25.md
cc @nikomatsakis 
Are there issues you'd like me to mention in the "Volunteers wanted" section?
=> Add notes for triage meeting 2019-04-25

procedures/crates.md
Fixes #57. There are still some unresolved questions, but we can work out the right answers in the PR comments.
cc @michaelwoerister (the additions are based on your work with `measureme`).
=> Finish out-of-tree crates policy.

procedures/crates.md
Originally suggested in https://github.com/rust-lang/rust/issues/57443
This project is a custom crate that is independent of rustc, but will keep our `toml` files in sync with the `lock` files (rationale, see linked issue). Instead of putting that code in-tree, I want it to start out of tree immediately, since it's generally useful.
=> Add a repository for cargo-lockfile-sync

working-groups/polonius/minutes/2019.05.28-meeting.md
As I only experienced the meeting reading it after the fact, I tried to be more precise this time and I hope I didn't make mistakes
=> Polonius WG: add meeting notes for 2019/05/28

.travis.yml
This PR makes sure that Rust is installed on Travis so that the simpleinfra static site deployment works.
=> Resolve issues with GitHub pages deployment

content/_index.md
Prepend links with the missing `/docs` to point to the correct location.
Fixes #127
=> Fix links to internal documentation

content/docs/experts/map.toml
This is part of #87, would be nice if others can jump in and suggest missing parts too :).
=> Add missing grammar directory to experts map

content/docs/working-groups/polonius/_index.md, content/docs/working-groups/polonius/minutes/2019.03.07-meeting.md, content/docs/working-groups/polonius/minutes/2019.04.23-meeting.md, content/docs/working-groups/polonius/minutes/2019.04.30-meeting.md, content/docs/working-groups/polonius/minutes/2019.05.07-meeting.md, content/docs/working-groups/polonius/minutes/2019.05.14-meeting.md, content/docs/working-groups/polonius/minutes/2019.05.28-meeting.md, content/docs/working-groups/polonius/minutes/2019.06.04-meeting.md, content/docs/working-groups/polonius/minutes/2019.06.11-meeting.md
This:
- adds a couple of Polonius meetings which were missed in the website transition
- adapt the markdown in the meeting notes from what Github allowed to what Hugo expects (e.g. lists, some h3/h4 section titles)
=> Update Polonius meeting notes

content/docs/experts/map.toml
This is the directories structure suggested by @Centril
=> Add parser directories to experts map

content/experts/map.toml
=> Fix invalid GitHub names in the expert map

content/experts/_index.md
Right now, clicking the link to the expert map downloads it to your machine. This isn't very convenient for viewing (or editing), so this makes it link to the file on Github.
Unfortunately this means we'll have to update the path anytime we move things around. I'm not sure how to get around that.
=> Link to Github view of expert map

content/experts/map.toml
I asked someone who could review a type layout change, and they mentioned the listed names.
=> Add type layout area to experts map

layouts/shortcodes/checkin-schedule.html
Turns out the week was starting from zero, and that's not how weeks work.
=> Resolve check-in schedule week being off-by-one.

.github/ISSUE_TEMPLATE/meeting-proposal.md
I wanted to learn how meetings work while reading https://github.com/rust-lang/compiler-team/issues/177 and noticed the URLs were broken.
Fixes #165.
=> Fix meeting proposal template URLs

content/minutes/design-meeting/2019-11-09-unified-dataflow-framework.md
These are the minutes for the meeting proposed in #202 "A unified framework for dataflow analysis".
=> Add design meeting minutes for 2019-11-08

content/minutes/design-meeting/2019-10-18-debuginfo-meeting.md
=> transcribed comments from github issue into a markdown doc.

content/minutes/design-meeting/2019-11-29-repl-meeting.md
=> REPL meeting minutes.

content/minutes/triage-meeting/2019-11-21.md
Sorry for the lateness on this; it's been a busy few weeks and I'm working on getting caught up.
=> Add weekly compiler team triage meeting notes for 2019-11-21

content/minutes/design-meeting/2019-12-06-end-to-end-query-PRs.md, content/minutes/design-meeting/2019-12-20-major-change-process.md
=> add minutes from 2019-12-06 meeting

content/working-groups/async-await/_index.md
[Rendered](https://github.com/rust-lang/compiler-team/blob/a2ac601dbe807f294fdf1db0a2cb84c1dc878fa9/content/working-groups/async-await/_index.md)
=> Update async-await page to point to team repo

content/_index.md, content/procedures/form-new-working-group.md, content/working-groups/prioritization/_index.md, layouts/shortcodes/checkin-schedule.html
cc @pnkfelix @nikomatsakis @wesleywiser
=> Form prioritization wg

content/minutes/design-meeting/2020-04-03-cranelift-backend-for-rustc.md
=> Add meeting notes for the cranelift backend design meeting

README.md
I came to this repo from https://www.rust-lang.org/governance/teams/compiler. I read the README five times scanning for the link to the rendered website until I realized it is up *above* the directory listing. I think this would have helped. :)
=> make link to rendered website easier to find

content/minutes/design-meeting/2020-05-29-Roadmap-2020-2021.md
=> add minutes from Roadmap 2020/2021 meeting

content/experts/map.toml
I noticed this link from https://github.com/rust-lang/rustc-dev-guide/pull/731/files#diff-a75a5daa4f7310d9e1bebc2021f72c16R26 and saw that rustdoc wasn't here at all!
r? @GuillaumeGomez 
Let me know if I missed anyone, I'm not sure exactly how the rustdoc team is setup.
=> Add rustdoc to 'experts' list

content/about/steering-meeting.md, content/menu/index.md, content/procedures/steering-meeting.md
Fix #334.
The steering-meeting changes are, I think, obviously better.
The only change I"m not sure about is the change so that "Compiler team
procedures" links to the specific compiler page on forge. The main problem I
have with that is that page itself does not actually document any procedures,
nor even *link* to subpages with such documentation.
* However, I justify this change by saying that I think in an ideal world, each
main page would have links to each of its subpages, because often the titles
alone in the Table-of-Contents on the left-hand side are not really enough
for a reader who arrives on the forge without any experience or context for
what they are looking for.
=> Eschew links to root page of forge.rlo

content/working-groups/polymorphization/_index.md
This PR updates the details of the polymorphization working group now that my master's project has finished.
Merge alongside rust-lang/team#398.
=> Update details of polymorphization working group

content/experts/map.toml
I was reading through https://rustc-dev-guide.rust-lang.org/mir/construction.html?highlight=hair#thir-and-mir-construction and https://rust-lang.github.io/compiler-team/experts/ and noticed this was outdated
=> hair -> thir in experts/map.toml

content/working-groups/parallel-rustc/_index.md, content/working-groups/polonius/_index.md, content/working-groups/rfc-2229/_index.md, content/working-groups/rustc-dev-guide/_index.md
Starting v0.65, hugo server emits errors for page not found. This fixes the issue, tested with latest version `Hugo Static Site Generator v0.75.1/extended darwin/amd64`
My understanding is this is because of `publishResources` that was introduced in https://github.com/gohugoio/hugo/releases/tag/v0.65.0. I wasn't able to make it work using the config flags.
My approach is documented as valid way of using `relref` here: https://gohugo.io/content-management/cross-references/
=> Fix compilation with latest hugo

README.md, content/menu/index.md, layouts/shortcodes/checkin-schedule.html
Discussed this with @spastorino on Zulip.
The `WG-prioritization` does not usually report during the compiler meeting (only when it is needed), so we can remove it from the regular scheduling.
**Notice**: due to the way the checkins are rotated, to avoid duplicated checkins from other WG, this PR should not be merged before **Friday October, 9th 2020**
Unrelated small changes:
- add a notice in the README to use the extended Hugo version for local testing
- fix a minor typo in the markdown
=> Remove WG-prioritization checkin

layouts/shortcodes/checkin-schedule.html
@spastorino I've investigated a bit this, this is a tentative patch to rectify how the date is calculated.
I _think_ the issue is when we try to convert to a string a Date such as `Thu Oct 22 2020 00:00:00 GMT+0200` instead of `2020-10-22`, you get `2020-10-21` which *could* be the reason for the off-by-one we experience. 
By adding five hours, we probably compensate for any time zone weirdness and thus converting `Thu Oct 22 2020 05:00:00 GMT+0200` returns `2020-10-22` which in the end is what we want (we don't care about timezones o DST in this calculation).
The visual result is this (at the time of writing):
```
Previous Week: 2020-10-15 - 2020-10-22 Rustc Dev Guide and LLVM
This Week: 2020-10-22 - 2020-10-29 Meta and MIR Optimizations
Next Week: 2020-10-29 - 2020-11-05 Polonius and …
```
=> Fix date conversion in meeting checkin assignment

triagebot.toml
This makes rustbot send the ping instead of the author of the MCP, making it possible for non-org-members to successfully ping the teams.
Would supersede #369.
Blocked on rust-lang/triagebot#914.
=> Ping compiler team and contributors when creating an MCP

content/working-groups/async-await/_index.md, content/working-groups/diagnostics/_index.md, content/working-groups/llvm/_index.md, content/working-groups/meta/_index.md, content/working-groups/mir-opt/_index.md, content/working-groups/nll/_index.md, content/working-groups/parallel-rustc/_index.md, content/working-groups/parselib/_index.md, content/working-groups/pgo/_index.md, content/working-groups/polonius/_index.md, content/working-groups/polymorphization/_index.md, content/working-groups/prioritization/_index.md, content/working-groups/rfc-2229/_index.md, content/working-groups/rls-2.0/_index.md, content/working-groups/rustc-dev-guide/_index.md, content/working-groups/self-profile/_index.md, content/working-groups/traits/_index.md, layouts/shortcodes/checkin-schedule.html
Link the rust-lang/team TOML files to have up-to-date members and leads when doing the meeting triage
(also mark wg-pgo as retired matching the document's contents)
r? @spastorino
=> link WG teams to rust-lang/team repo

content/working-groups/rls-2.0/_index.md
It was renamed to `#t-compiler/rust-analyzer` to be easier to find
=> Update the rust-analyzer Zulip stream

layouts/shortcodes/checkin-schedule.html
With the sprint model that we use, the Polonius working group has relatively infrequent activity, so much so that the check-ins at the compiler meetings happen before any substantial work has been completed. 
A lot of the times there's little to report, so this PR removes the WG from the check-in rotation, as we've discussed before with @nikomatsakis.
r? @nikomatsakis 
---
Note: I apparently didn't have to change the "magic number" so that the expected order for other WGs remains the same. Here's a screenshot of how this PR looks locally: the next 4 WGs are the same [as mentioned on the website](https://rust-lang.github.io/compiler-team/about/triage-meeting/)
=> Remove wg-polonius from compiler meeting check-ins

triagebot.toml
Hi,
as per my question on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/triagebot.20.60relabel.60.20command.20for.20rust-lang.2Fcompiler-team.20repo), having the bot respond to a `label` command would help me a bit :-)
thanks
=> Add relabel command to triagebot

.github/ISSUE_TEMPLATE/major_change.md
There are two links to the MCP, one of which used to link to the top-level forge page. The footnoted URL for the top-level forge page was unreferenced.
=> Drop unreferenced footnoted link to forge

.github/ISSUE_TEMPLATE/major_change.md
After seeing what Zulip produced for [a recent MCP topic](https://zulip-archive.rust-lang.org/233931tcompilermajorchanges/42921CIshouldexercisesubsetoftestsundecompilerteam439.html), I figured it might be good to nudge people in the right direction here.
=> suggest people limit title length in MCP template

content/procedures/crates.md
=> remove invalid link to rust-lang/cargo-lockfile-sync

content/working-groups/_index.md
Previously, people would have had to figure out that "mentored issues" referred to the "E-mentor" label themselves, and constructed a query by hand.
=> Link to E-mentor issues

content/working-groups/llvm/_index.md
LLVM has migrated from Phabricator to GitHub.
r? cuviper
=> Update the LLVM guide link

content/experts/map.toml
This file is an attractive nuisance that inspires people to bother contributors who have decided their time with the project is done. Perhaps it should be simply deleted wholesale. That seems like a somewhat radical position, so I merely culled several names that haven't contributed to the compiler recently, or that I recognize as having actively decided to distance themselves. Or, in one case, an officially-over project.
=> Remove several alumni from experts/map.toml

content/_index.md
Now using the new rust-lang/calendar version instead of Google Calendar
=> Update compiler links

content/procedures/_index.md
The text is _copied_ from content/menu/index.md:17, so this is a bit of a problem currently. I'm also not sure how much sense that even makes, since the directory pages have vastly differing content: [About](content/about/_index.md) has just a heading line, but [Minutes](content/minutes/_index.md) also has nothing.
=> Add landing page text #732

content/menu/index.md
companion fix for #733 
this adds a more concise menu item wording for the page linking to the T-compiler procedures
=> improve index item wording

content/working-groups/polymorphization/_index.md, content/working-groups/self-profile/_index.md, content/working-groups/traits/_index.md
These status updates were discussed with the current leads.
=> Update status for some WGs

triagebot.toml
CC https://github.com/rust-lang/compiler-team/issues/757
T-compiler-contributors is dead, long live T-compiler!
=> Make triagebot stop mentioning T-compiler-contributors in its MCP messages

.github/ISSUE_TEMPLATE/major_change.md
It is replaced by rustbot important message which does the same thing in a more visible and *hopefully* more effective manner, cf. https://github.com/rust-lang/triagebot/pull/1902
cc @apiraino *(as you suggested)*
=> Remove the Comments section in the MCP template

content/minutes/triage-meeting/T-compiler Meeting Agenda 2025-02-06.md, content/minutes/triage-meeting/T-compiler Meeting Agenda 2025-02-13.md, content/minutes/triage-meeting/T-compiler Meeting Agenda 2025-02-20.md, content/minutes/triage-meeting/T-compiler Meeting Agenda 2025-02-27.md
This will be the last batch of meetings notes added to the repository.
From now they will just be linked from their HackMD location
https://hackmd.io/team/rust-compiler-team?nav=overview&tags=%5B%22weekly%22%5D&tagtree-filter=true:
=> Add t-compiler triage meetings notes 02/25

.github/ISSUE_TEMPLATE/major_change.md
It was pointing to a page that was 404.
=> Fix link in MCP issue template

README.md, layouts/partials/docs/html-head.html
This should make the link in the description of this git repository redirect to where we now have the team compiler documentation.
I wanted to do it properly with a Hugo configuration option but didn't find a way :man_shrugging: 
r? @davidtwco 
thanks!
=> Add a redirect to forge

.github/ISSUE_TEMPLATE/major_change.md
To hopefully make it less likely for people to forget to change their MCP issue title.
See [#t-compiler/major changes > Retroactive MCP for the Rust for Linux Ec… compiler-team#874 @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/233931-t-compiler.2Fmajor-changes/topic/Retroactive.20MCP.20for.20the.20Rust.20for.20Linux.20Ec.E2.80.A6.20compiler-team.23874/near/520992619)
r? @apiraino
=> Use blank issue title for MCP issue template

triagebot.toml
Proposed at [#t-compiler > Automatic closing of MCP after second @ 💬](https://rust-lang.zulipchat.com/#narrow/channel/131828-t-compiler/topic/Automatic.20closing.20of.20MCP.20after.20second/near/524306690)
=> Enable auto-closing of MCP in triagebot

.github/ISSUE_TEMPLATE/major_change.md
cf. Forge side: https://github.com/rust-lang/rust-forge/pull/912.
Compared to the current version, this PR modifies:
> A compiler team member or contributor who is knowledgeable in the area can **second** by writing `@rustbot second`.
- Compiler team contributors is not a thing now.
- MCPs can be approved both by **second** or by full team **FCP**, so include both "equally" here immediately.
> * Finding a "second" suffices for internal changes. If however, you are proposing a new public-facing feature, such as a `-C flag`, then full team check-off is required.
Delegate to Forge docs <https://forge.rust-lang.org/compiler/proposals-and-stabilization.html> instead of trying to reproduce a less complete subset here.
> * Once an MCP is seconded, the Final Comment Period begins. If no …
=> Update the MCP issue template to clarify the process
