- README.md
- working-groups/.template/FAQ.md
- working-groups/.template/NOTES.md
- working-groups/.template/README.md
- working-groups/README.md
Please feel free to add comments and suggestions. You can find [a rendered version here](https://github.com/davidtwco/compiler-team/tree/working-group-template). You can find the [Zulip topic for this here](https://rust-lang.zulipchat.com/#narrow/stream/185694-t-compiler.2Fwg-meta/topic/WG.20template/near/159104409) and [the meeting that spawned this here](https://rust-lang.zulipchat.com/#narrow/stream/185694-t-compiler.2Fwg-meta/topic/meeting.202019.2E02.2E21/near/159099063).
> Initial draft of working group template.

- working-groups/async-await/README.md
This maybe wants to be something on the template?
> Mention the YouTube playlist

- README.md
- working-groups/llvm/FAQ.md
- working-groups/llvm/NOTES.md
- working-groups/llvm/README.md
Does that look right @nikomatsakis?
> Add WG-LLVM

- working-groups/rls-2.0/README.md
r? @Xanewok 
As you are digging into the code right now, I would be curious to here how to best organize existing docs :)
> link RLS 2.0 play list

- working-groups/self-profile/NOTES.md
> Add notes from self-profiler WG meeting

- minutes/steering-meeting/2019.03.01.md
- minutes/steering-meeting/2019.03.02.md
I'll post this on the [internals thread](https://internals.rust-lang.org/t/compiler-steering-meeting/8588/47) once merged.
> Add steering meeting minutes for 02/03/19

- working-groups/meta/NOTES.md
r? @nikomatsakis 
/cc @davidtwco
> Add journeypeople and team member minutes from 2019-02-28 meeting

- working-groups/polonius/FAQ.md
- working-groups/polonius/README.md
> add definition for polonius wg

- working-groups/llvm/README.md
> Fix broken image in README for LLVM working group

- working-groups/mir-opt/NOTES.md
> Clean up mir-opt notes

- working-groups/llvm/README.md
Added links and brief descriptions to some introductory resources
on LLVM and codegen.
CC: @nagisa @nikic
> Add resources to wg-llvm

- procedures/form-new-working-group.md
- working-groups/mir-opt/README.md
Sister PR: rust-lang/team#42
cc @nikomatsakis @pietroalbini
> Mention updating rust-lang/team

- working-groups/rls-2.0/README.md
Let's give this work-list thingy a try!
> link worklist

- README.md
- about/triage-meeting.md
- working-groups/pipelining/FAQ.md
- working-groups/pipelining/NOTES.md
- working-groups/pipelining/README.md
Requested by Niko to formalize the effort to pipeline rustc a bit more,
so this adds a bunch of tracking information and such for the efforts
here on the rustc side of things!
> Add a pipelining WG

- working-groups/rls-2.0/NOTES.md
> add notes for mbe meeting

- minutes/triage-meeting/2019-04-11.md
cc @nikomatsakis 
I'll create a post in irlo after this is approved.
> Add triage meeting notes for 2019-04-11

- README.md
- working-groups/polonius/README.md
- working-groups/polonius/minutes/2019.03.07-meeting.md
A couple links and typo fixes, and an appearance in the Big Table™
> Some more polonius content

- minutes/triage-meeting/2019-04-18.md
I'll cross post to the irlo thread when this is approved. 
cc @nikomatsakis
> Add notes for triage meeting 2019-04-18

- README.md
- working-groups/learning/FAQ.md
- working-groups/learning/NOTES.md
- working-groups/learning/README.md
@nikomatsakis @davidtwco I've opened this PR as a starting point so we can discuss.
> Add Learning WG

- procedures/call-for-participation.md
We [briefly discussed the idea of a "call for participation" thread][z] -- here is a quick and dirty template and some notes.
[z]: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/call.20for.20participation
> proposed "call for participation" template

- about/steering-meeting.md
- procedures/steering-meeting.md
- proposals/_template.md
This is a proposal for how to do the "design meetings" that we talked about at [the last steering meeting](https://github.com/rust-lang/compiler-team/blob/master/minutes/steering-meeting/2019.04.12.md). I kind of made a bunch of things up, trying to do my best to match what we said in the meeting. Thoughts?
cc @michaelwoerister @eddyb 
Fixes #59
> propose to use the steering meeting for all manner of discussion

- minutes/triage-meeting/2019-05-02.md
> Add triage meeting notes for 2019-05-02

- .github/ISSUE_TEMPLATE/meeting-proposal.md
- README.md
I think this matches what we said in today's meeting.
> rough meeting template

- experts/MAP.md
- experts/map.toml
I'm opening this as a starting point for discussion. In particular we need to fill the directories structure.
Please send me edit requests :).
Closes #63
> Add experts map as toml file

- working-groups/diagnostics/NOTES.md
- working-groups/diagnostics/README.md
> First wg-diagnostics meeting post mortem

- working-groups/parallel-rustc/minutes/2019.05.10.md
> Add the minutes of parallel-rustc planning meeting

- minutes/design-meeting/2019-06-21-the-gcx-tcx-transition.md
Closes https://github.com/rust-lang/compiler-team/issues/104
> Add minutes from "discuss the great gcx, tcx transition"

- working-groups/learning/minutes/2019.07.09-meeting.md
> WG learning meeting notes

- .gitignore
- .travis.yml
This *should* work, but I've not been able to test on my fork due to a Travis error ("GitHub Pages branch not included via configuration").
cc @spastorino @pietroalbini
> Add .travis.yml for GitHub pages deployment.

- config.toml
🌟 Adding the base URL on config.toml file
> adding base URL

- content/docs/experts/map.toml
> add lexer area and associated experts

- content/_index.md
- content/experts/map.toml
- content/minutes/triage-meeting/2019-07-04.md
- content/minutes/triage-meeting/2019-07-11.md
- content/minutes/triage-meeting/2019-07-25.md
- content/working-groups/polonius/_index.md
- content/working-groups/polonius/minutes/2019.03.07-meeting.md
- content/working-groups/polonius/minutes/2019.04.23-meeting.md
- content/working-groups/polonius/minutes/2019.04.30-meeting.md
- content/working-groups/polonius/minutes/2019.05.07-meeting.md
- content/working-groups/polonius/minutes/2019.05.14-meeting.md
- content/working-groups/polonius/minutes/2019.05.28-meeting.md
- content/working-groups/polonius/minutes/2019.06.04-meeting.md
- content/working-groups/polonius/minutes/2019.06.11-meeting.md
> Add lost information after remove of docs/

- content/experts/map.toml
I also nominate @Zoxc as an expert in the area, I hope they're okay with that =P
> Add directories to generators area

- content/working-groups/learning/minutes/2019.08.06-meeting.md
minutes of today's meeting for Learning WG.
> Learning WG: adds new minutes

- content/experts/map.toml
> Add myself to the experts map for macro_rules

- content/working-groups/learning/_index.md
- content/working-groups/learning/minutes/2019.08.20-meeting.md
> Update meeting notes

- content/working-groups/parallel-rustc/minutes/2019.05.10.md
> update minutes from shipping parallel rustc

- content/working-groups/polonius/_index.md
They've been playing this role for a while. Let's make it official!
> add lqd as co-lead of polonius wg

- content/working-groups/parallel-rustc/_index.md
Since Aaron has effectively already taken over as lead `:)`
r? @aturon
> Update leads of parallelization WG.

- content/minutes/design-meeting/2019-09-13-rust-analyzer-and-libraryification.md
> add minutes from rust-analyzer meeting

- content/working-groups/learning/minutes/2019.09.17-meeting.md
Learning WG: Meeting minutes for 2019-09-17.
> Learning WG: Update meeting notes

- content/menu/index.md
- content/minutes/design-meeting/_index.md
- content/minutes/steering-meeting/_index.md
- content/minutes/triage-meeting/_index.md
- layouts/shortcodes/list-files.html
This fixes the main problem described in https://github.com/rust-lang/compiler-team/issues/153
Still we may want to add the last 3 meeting to the menu.
> Generate full list of meetings

- content/minutes/design-meeting/2019-09-20-target-tier-policy.md
> Add minutes from Target Tier Policy meeting

- content/working-groups/learning/minutes/2019.10.01-meeting.md
> Learning WG: Update meeting notes 2019-10-01

- content/minutes/design-meeting/2019-09-27-place-interning.md
Add minutes from [this meeting](https://rust-lang.zulipchat.com/#narrow/stream/189540-t-compiler.2Fwg-mir-opt/topic/Place's.20projection.20interning.20design.20meeting.20.3F)
> Add Place interning minutes notes

- content/working-groups/parallel-rustc/minutes/2019.09.30-planning.md
Add minutes from [this meeting](https://rust-lang.zulipchat.com/#narrow/stream/187679-t-compiler.2Fwg-parallel-rustc/topic/planning.20meeting)
> Add Parallel WG planning meeting minutes

- content/minutes/triage-meeting/2019-10-10.md
> Add notes for compiler team triage meeting on 2019-10-10.

- content/working-groups/learning/_index.md
Add recently minutes to the list
> Update wg-learning minutes

- content/minutes/triage-meeting/2019-10-24.md
> Add compiler team triage meeting notes for 2019-10-24

- content/minutes/design-meeting/2019-11-01-streaming-dep-graph-proposal.md
Cut and pasted from source for https://hackmd.io/9GgAXPtrRSiwBPsI6saa_A?view
> Minutes from today's "streaming dep graph" design meeting

- content/minutes/design-meeting/2019-11-16-Working-Group-Retrospective.md
Closes https://github.com/rust-lang/compiler-team/issues/187
> add minutes from 2019-11-16 meeting

- content/_index.md
- content/working-groups/pgo/_index.md
> Send WG-profile-guided-optimization into retirement.

- content/_index.md
- content/working-groups/polymorphization/_index.md
- layouts/shortcodes/checkin-schedule.html
Working group to track the polymorphization work that I'm doing for my Master's thesis. I've made a private Zulip stream which this PR's content links to, will make public once merged. Requested by @nikomatsakis.
> Add polymorphization working group.

- content/minutes/design-meeting/2019-12-20-major-change-process.md
> summarize design meeting from 2019-12-20 on major change process

- content/working-groups/learning/_index.md
r? @spastorino 
Is this what you were thinking of?
cc @rust-lang/wg-learning
> Add a bit more about our process

- content/minutes/design-meeting/2020-03-12-shared-library-for-types.md
> add minutes from 2020-03-12 design meeting

- content/minutes/design-meeting/2020-02-28-focused-and-efficient-triage.md
> Add minutes of Focused and Efficient Triage Design Meeting

- .travis.yml
> travis: update build config import format

- .github/ISSUE_TEMPLATE/major_change.md
As per the proposed process from https://github.com/rust-lang/compiler-team/blob/master/content/minutes/design-meeting/2019-12-20-major-change-process.md#final-proposed-process
> Create major_change issue template

- content/experts/map.toml
- content/working-groups/diagnostics/_index.md
- content/working-groups/mir-opt/_index.md
Reflect recent crates/modules renaming.
> Update crates/modules names

- layouts/shortcodes/checkin-schedule.html
> Add magic number hack to "fix" checkins schedule

- content/working-groups/traits/_index.md
Closes #185
r? @nikomatsakis @pnkfelix
> Add traits leads

- .github/ISSUE_TEMPLATE/major_change.md
> update major change proposal template to match the RFC

- content/experts/map.toml
I've done a fair amount of work on the match exhaustiveness code, so I thought it made sense for me to be listed on here. Let me know if this is ok.
> Add myself to the experts map

- content/about/chat-platform.md
Discord has been archived and IRC is no more.
> Update chat platform information

- content/working-groups/rfc-2229/_index.md
r? @spastorino 
cc @nikomatsakis
> Update WG-2229 page

- content/working-groups/prioritization/_index.md
@spastorino I've tried updating this page, I think there is some content outdated.
Can you have a look if my changes make sense?
Thanks :-)
> Update WG-prioritization page

- layouts/shortcodes/checkin-schedule.html
> Use a JavaScript object to relate wg names and urls

- layouts/shortcodes/checkin-schedule.html
cc @pnkfelix @spastorino 
Related to #299
> Add wg-incr-comp to the checkin schedule

- content/experts/map.toml
cc @Mark-Simulacrum, @ehuss - do the 'familiar' and 'experts' sections look right? Did I miss anyone?
> Update Rustdoc section and add bootstrap

- .github/ISSUE_TEMPLATE/major_change.md
Our instructions for MCPs weren't obvious just from the template, so I'm trying to solve this with more text, not sure if that is the best idea, but the only one that was obvious to me.
> Clarify a point on the MCP template

- content/experts/map.toml
- Fixed directory paths
- Alphabetized user lists
- Removed inactive contributors
> Update expert map

- content/_index.md
Should work in theory, I haven't tested locally.
> Fix license paths

- .github/ISSUE_TEMPLATE/major_change.md
> Fix typo: then → them

- content/about/chat-platform.md
I thought I'd take my first baby-steam of contributing to rust-compiler with a small PR for the hugo site.
If appreciated, then I'd look for more opportunities to improve the site and take it from there.
> Add header to chat-platform.md, separate lines and add direct links to streams mentioned
